### ISSUE TITLE
Handling of Reference DU Items in BOM Extraction

### ISSUE THREAD

**Issue by hariharan-isgec** [Isgec/BOMExportEDI#1]
In the Drawings DU List there are DU items which itself is a drawing containing BOM and it is given in the major assembly draing as a Reference
The drawing practice will be modified so that a new item type will be added ( R-Reference) and wherever the item has item type “R” , the program will identify this item as a child of some other child and will not load in in the Child/Part item for this Drawing but will store in a New Table Called Referenced Child Items.

Action By: @veena-isgec (for LN related Tables), @0340LalitGupta for BOM Extraction

**Comment by 0340LalitGupta** [comment]
No problem reported. Issue can be closed. @hariharan-isgec
